
package vista;

import Imagenes.fondovistas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leone
 */
public class Mostrar extends javax.swing.JInternalFrame {

 private static Connection con;
 private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass="";
    private static final String url="jdbc:mysql://localhost:3306/bdnomina";
    String cod;
    String cod2;
        public void conector() {
        // Reseteamos a null la conexion a la bd
        con=null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            con= (Connection) DriverManager.getConnection(url, user, pass);
            // Si la conexion fue exitosa mostramos un mensaje de conexion exitosa
            if (con!=null){
                ESTADO.setText("Conexion establecida");
            }
        }
        // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e){
            ESTADO.setText("Error de conexion" + e);
        }
    }
    /**
     * Creates new form BajasEmpleados
     */
    public Mostrar() {
        initComponents();
        Label5.setBorder(new fondovistas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CodigoE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        txt_puesto = new javax.swing.JLabel();
        txt_estado = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        ESTADO = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_sueldo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CodigoN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        SueldoE = new javax.swing.JLabel();
        Boni = new javax.swing.JLabel();
        Comi = new javax.swing.JLabel();
        Otros = new javax.swing.JLabel();
        Des = new javax.swing.JLabel();
        Anti = new javax.swing.JLabel();
        TotalD = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(570, 570));
        setMinimumSize(new java.awt.Dimension(570, 570));
        setPreferredSize(new java.awt.Dimension(570, 570));
        setVisible(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(125, 72, 39, 28);
        getContentPane().add(CodigoE);
        CodigoE.setBounds(179, 72, 91, 30);

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(125, 109, 46, 28);

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(125, 146, 46, 28);

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel4.setText("Puesto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(125, 183, 38, 28);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(126, 257, 39, 28);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(184, 119, 178, 16);
        getContentPane().add(txt_apellido);
        txt_apellido.setBounds(186, 156, 178, 16);
        getContentPane().add(txt_puesto);
        txt_puesto.setBounds(179, 183, 178, 14);
        getContentPane().add(txt_estado);
        txt_estado.setBounds(180, 269, 178, 14);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(288, 71, 90, 23);
        getContentPane().add(ESTADO);
        ESTADO.setBounds(232, 514, 0, 0);

        jLabel11.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel11.setText("Sueldo:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(126, 220, 39, 28);
        getContentPane().add(txt_sueldo);
        txt_sueldo.setBounds(179, 220, 178, 26);

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel10.setText("Sueldo Extraordinario:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(23, 383, 119, 28);

        jLabel13.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel13.setText("Bonificación:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(23, 419, 68, 28);

        jLabel14.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel14.setText("Comisiones:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 450, 62, 28);

        jLabel15.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel15.setText("Otros:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 480, 32, 28);

        jLabel16.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel16.setText("Anticipos:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(321, 419, 52, 28);

        jLabel17.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel17.setText("Descuentos:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(321, 383, 64, 28);

        jLabel18.setFont(new java.awt.Font("Javanese Text", 1, 13)); // NOI18N
        jLabel18.setText("Bonos");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(23, 346, 51, 31);

        jLabel19.setFont(new java.awt.Font("Javanese Text", 1, 13)); // NOI18N
        jLabel19.setText("Descuentos");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(321, 346, 74, 31);

        jLabel20.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel20.setText("Total Devengado");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(321, 456, 89, 28);

        jLabel6.setFont(new java.awt.Font("Javanese Text", 1, 20)); // NOI18N
        jLabel6.setText("MOSTRAR NOMINA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(179, 8, 212, 52);
        getContentPane().add(CodigoN);
        CodigoN.setBounds(213, 302, 90, 30);

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(321, 301, 90, 23);
        getContentPane().add(SueldoE);
        SueldoE.setBounds(150, 390, 100, 16);
        getContentPane().add(Boni);
        Boni.setBounds(150, 420, 100, 16);
        getContentPane().add(Comi);
        Comi.setBounds(150, 450, 100, 16);
        getContentPane().add(Otros);
        Otros.setBounds(150, 480, 100, 16);
        getContentPane().add(Des);
        Des.setBounds(420, 390, 99, 16);
        getContentPane().add(Anti);
        Anti.setBounds(420, 420, 99, 16);
        getContentPane().add(TotalD);
        TotalD.setBounds(415, 456, 90, 16);

        jLabel25.setFont(new java.awt.Font("Javanese Text", 0, 11)); // NOI18N
        jLabel25.setText("Codigo Nomina");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(122, 302, 73, 26);
        getContentPane().add(Label5);
        Label5.setBounds(0, 0, 560, 525);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:  
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdnomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from templeados where codigoE = ?");
            pst.setString(1, CodigoE.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txt_nombre.setText(rs.getString("nombreE"));
                txt_apellido.setText(rs.getString("apellidoE"));
                txt_puesto.setText(rs.getString("puestoE"));
                txt_sueldo.setText(rs.getString("sueldoE"));
                txt_estado.setText(rs.getString("estadoE"));
                cod=CodigoE.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no registrado.");
            CodigoE.setText("");
            }
            
        }catch (Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdnomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from tCheques where codigoC = ?");
            pst.setString(1, CodigoN.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                SueldoE.setText(rs.getString("extraordinarioC"));
                Boni.setText(rs.getString("bonificacionC"));
                Comi.setText(rs.getString("comisionesC"));
                Otros.setText(rs.getString("otrosC"));
                Des.setText(rs.getString("descuentoC"));
                Anti.setText(rs.getString("anticipoC"));
                TotalD.setText(rs.getString("totalC"));
                cod2=CodigoN.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no registrado.");
            CodigoN.setText("");
            }
            
        }catch (Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anti;
    private javax.swing.JLabel Boni;
    private javax.swing.JTextField CodigoE;
    private javax.swing.JTextField CodigoN;
    private javax.swing.JLabel Comi;
    private javax.swing.JLabel Des;
    private javax.swing.JLabel ESTADO;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Otros;
    private javax.swing.JLabel SueldoE;
    private javax.swing.JLabel TotalD;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_estado;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_puesto;
    private javax.swing.JLabel txt_sueldo;
    // End of variables declaration//GEN-END:variables
}
